export const WEEKS = [
  {
    id: 1, title: "Arrays, Hashing & Python", accent: "#EF4444",
    days: [
      { day: "Mon", tag: "NO DRIVE", tasks: [
        { id:"w1m1", text:"LC: Two Sum (Easy)", type:"dsa", link:"https://leetcode.com/problems/two-sum/" },
        { id:"w1m2", text:"LC: Contains Duplicate (Easy)", type:"dsa", link:"https://leetcode.com/problems/contains-duplicate/" },
        { id:"w1m3", text:"LC: Valid Anagram (Easy)", type:"dsa", link:"https://leetcode.com/problems/valid-anagram/" },
        { id:"w1m4", text:"Set up: Python 3.11+, VS Code, venv", type:"setup", link:"https://code.visualstudio.com/docs/python/python-tutorial" },
        { id:"w1m5", text:"CS50P Lecture 0: Functions + Variables", type:"ml", link:"https://cs50.harvard.edu/python/" },
        { id:"w1m6", text:"Install Git, create GitHub account", type:"setup", link:"https://git-scm.com/book/en/v2/Getting-Started-Installing-Git" },
        { id:"w1m7", text:"GitHub Skills: Introduction to GitHub", type:"project", link:"https://skills.github.com/" },
        { id:"w1m8", text:"Create first repo — init, add, commit, push", type:"project", link:"https://learngitbranching.js.org/" },
      ]},
      { day: "Tue", tag: "DRIVE 5-9", tasks: [
        { id:"w1t1", text:"LC: Group Anagrams (Medium)", type:"dsa", link:"https://leetcode.com/problems/group-anagrams/" },
        { id:"w1t2", text:"LC: Top K Frequent Elements (Medium)", type:"dsa", link:"https://leetcode.com/problems/top-k-frequent-elements/" },
        { id:"w1t3", text:"CS50P Lecture 1: Conditionals", type:"ml", link:"https://cs50.harvard.edu/python/" },
        { id:"w1t4", text:"Build: CLI expense tracker (read/write JSON)", type:"project" },
        { id:"w1t5", text:"Read: MDN HTTP Overview", type:"llm", link:"https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview" },
        { id:"w1t6", text:"Install requests, first API call (Open-Meteo)", type:"llm", link:"https://requests.readthedocs.io/en/latest/" },
      ]},
      { day: "Wed", tag: "NO DRIVE", tasks: [
        { id:"w1w1", text:"LC: Product of Array Except Self (Medium)", type:"dsa", link:"https://leetcode.com/problems/product-of-array-except-self/" },
        { id:"w1w2", text:"LC: Encode and Decode Strings (Medium)", type:"dsa", link:"https://leetcode.com/problems/encode-and-decode-strings/" },
        { id:"w1w3", text:"CS50P Lecture 2: Loops", type:"ml", link:"https://cs50.harvard.edu/python/" },
        { id:"w1w4", text:"Python tutorial: Lists, Dicts, Sets", type:"ml", link:"https://docs.python.org/3/tutorial/" },
        { id:"w1w5", text:"Finish CLI expense tracker + error handling", type:"project" },
        { id:"w1w6", text:"Push expense tracker to GitHub with README", type:"project" },
        { id:"w1w7", text:"Learn Git Branching: first 8 levels", type:"project", link:"https://learngitbranching.js.org/" },
      ]},
      { day: "Thu", tag: "DRIVE 5-9", tasks: [
        { id:"w1h1", text:"LC: Longest Consecutive Sequence (Medium)", type:"dsa", link:"https://leetcode.com/problems/longest-consecutive-sequence/" },
        { id:"w1h2", text:"Review: re-solve Product of Array cold", type:"dsa", link:"https://leetcode.com/problems/product-of-array-except-self/" },
        { id:"w1h3", text:"CS50P Lecture 3: Exceptions", type:"ml", link:"https://cs50.harvard.edu/python/" },
        { id:"w1h4", text:"Build: Weather API script (Open-Meteo)", type:"project", link:"https://open-meteo.com/en/docs" },
        { id:"w1h5", text:"Learn: env variables, .env files, API keys", type:"llm" },
        { id:"w1h6", text:"Read: REST API Tutorial", type:"llm", link:"https://restfulapi.net/" },
      ]},
      { day: "Fri", tag: "DRIVE 4-9", tasks: [
        { id:"w1f1", text:"LC: Valid Sudoku (Medium)", type:"dsa", link:"https://leetcode.com/problems/valid-sudoku/" },
        { id:"w1f2", text:"Build: Weather CLI app (combine everything)", type:"project" },
        { id:"w1f3", text:"CS50P Lecture 4: Libraries", type:"ml", link:"https://cs50.harvard.edu/python/" },
        { id:"w1f4", text:"WEEKLY RETRO: log hours, push all code", type:"review" },
        { id:"w1f5", text:"Read: Python async/await intro", type:"llm", link:"https://realpython.com/async-io-python/" },
      ]},
      { day: "Sat", tag: "DRIVE 12-8", tasks: [
        { id:"w1s1", text:"LC Review: re-solve 3 problems timed", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w1s2", text:"LC: Longest Substring No Repeat (Medium)", type:"dsa", link:"https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
        { id:"w1s3", text:"SQLBolt lessons 1-6 (SELECT, WHERE)", type:"project", link:"https://sqlbolt.com/" },
        { id:"w1s4", text:"Install SQLite, create sample DB", type:"project" },
      ]},
      { day: "Sun", tag: "DRIVE 12-8", tasks: [
        { id:"w1u1", text:"LC: re-solve 2 problems you struggled with", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w1u2", text:"CS50P Lecture 5: Unit Tests", type:"ml", link:"https://cs50.harvard.edu/python/" },
        { id:"w1u3", text:"SQLBolt lessons 7-12 (JOINs, GROUP BY)", type:"project", link:"https://sqlbolt.com/" },
        { id:"w1u4", text:"Plan next week, push all code", type:"review" },
      ]},
    ],
  },
  {
    id: 2, title: "Two Pointers, Sliding Window & FastAPI", accent: "#F97316",
    days: [
      { day: "Mon", tag: "NO DRIVE", tasks: [
        { id:"w2m1", text:"LC: Valid Palindrome (Easy)", type:"dsa", link:"https://leetcode.com/problems/valid-palindrome/" },
        { id:"w2m2", text:"LC: Two Sum II (Medium)", type:"dsa", link:"https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
        { id:"w2m3", text:"LC: 3Sum (Medium) — classic!", type:"dsa", link:"https://leetcode.com/problems/3sum/" },
        { id:"w2m4", text:"FastAPI Tutorial: First Steps + Path Params", type:"project", link:"https://fastapi.tiangolo.com/tutorial/" },
        { id:"w2m5", text:"FastAPI: Query Params + Request Body + Pydantic", type:"project", link:"https://fastapi.tiangolo.com/tutorial/body/" },
        { id:"w2m6", text:"Build: TODO API (GET /todos, POST /todos)", type:"project" },
      ]},
      { day: "Tue", tag: "DRIVE 5-9", tasks: [
        { id:"w2t1", text:"LC: Container With Most Water (Medium)", type:"dsa", link:"https://leetcode.com/problems/container-with-most-water/" },
        { id:"w2t2", text:"LC: Best Time to Buy/Sell Stock (Easy)", type:"dsa", link:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
        { id:"w2t3", text:"Pandas: '10 Minutes to Pandas' tutorial", type:"ml", link:"https://pandas.pydata.org/docs/user_guide/10min.html" },
        { id:"w2t4", text:"Continue TODO API: PUT, DELETE, errors", type:"project" },
        { id:"w2t5", text:"fast.ai Lesson 1 (first half)", type:"ml", link:"https://course.fast.ai/" },
      ]},
      { day: "Wed", tag: "NO DRIVE", tasks: [
        { id:"w2w1", text:"LC: Longest Substring No Repeating (Medium)", type:"dsa", link:"https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
        { id:"w2w2", text:"LC: Longest Repeating Char Replacement (Medium)", type:"dsa", link:"https://leetcode.com/problems/longest-repeating-character-replacement/" },
        { id:"w2w3", text:"Kaggle Pandas: Lessons 1-3", type:"ml", link:"https://www.kaggle.com/learn/pandas" },
        { id:"w2w4", text:"Add SQLite database to TODO app", type:"project" },
        { id:"w2w5", text:"fast.ai Lesson 1 (finish) — train first model", type:"ml", link:"https://course.fast.ai/" },
      ]},
      { day: "Thu", tag: "DRIVE 5-9", tasks: [
        { id:"w2h1", text:"LC: Minimum Window Substring (Hard)!", type:"dsa", link:"https://leetcode.com/problems/minimum-window-substring/" },
        { id:"w2h2", text:"Kaggle Pandas: Lessons 4-5", type:"ml", link:"https://www.kaggle.com/learn/pandas" },
        { id:"w2h3", text:"Polish TODO API: Pydantic models, validation", type:"project" },
        { id:"w2h4", text:"Push TODO API to GitHub with README", type:"project" },
        { id:"w2h5", text:"Read: Python async/await deep dive", type:"llm", link:"https://realpython.com/async-io-python/" },
      ]},
      { day: "Fri", tag: "DRIVE 4-9", tasks: [
        { id:"w2f1", text:"LC: Permutation in String (Medium)", type:"dsa", link:"https://leetcode.com/problems/permutation-in-string/" },
        { id:"w2f2", text:"Add /stats endpoint to TODO API", type:"project" },
        { id:"w2f3", text:"WEEKLY RETRO: log hours, push code", type:"review" },
        { id:"w2f4", text:"Review: re-solve Min Window Substring", type:"dsa", link:"https://leetcode.com/problems/minimum-window-substring/" },
      ]},
      { day: "Sat", tag: "DRIVE 12-8", tasks: [
        { id:"w2s1", text:"LC Review: 3Sum + Longest Substring timed", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w2s2", text:"LC: Trapping Rain Water (Hard)", type:"dsa", link:"https://leetcode.com/problems/trapping-rain-water/" },
        { id:"w2s3", text:"Deploy TODO API with uvicorn, test all", type:"project", link:"https://fastapi.tiangolo.com/deployment/" },
        { id:"w2s4", text:"fast.ai Lesson 2: Deployment (start)", type:"ml", link:"https://course.fast.ai/" },
      ]},
      { day: "Sun", tag: "DRIVE 12-8", tasks: [
        { id:"w2u1", text:"LC drill: 2-3 Two Pointer/Sliding Window", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w2u2", text:"fast.ai Lesson 2 (finish): SGD from scratch", type:"ml", link:"https://course.fast.ai/" },
        { id:"w2u3", text:"Add pytest tests to TODO API", type:"project", link:"https://docs.pytest.org/en/stable/" },
        { id:"w2u4", text:"Push everything, plan Week 3", type:"review" },
      ]},
    ],
  },
  {
    id: 3, title: "Binary Search, Stack & First LLM Call", accent: "#10B981",
    days: [
      { day: "Mon", tag: "NO DRIVE", tasks: [
        { id:"w3m1", text:"LC: Binary Search (Easy)", type:"dsa", link:"https://leetcode.com/problems/binary-search/" },
        { id:"w3m2", text:"LC: Search a 2D Matrix (Medium)", type:"dsa", link:"https://leetcode.com/problems/search-a-2d-matrix/" },
        { id:"w3m3", text:"LC: Koko Eating Bananas (Medium)", type:"dsa", link:"https://leetcode.com/problems/koko-eating-bananas/" },
        { id:"w3m4", text:"Karpathy Ep 1: Micrograd (first half)", type:"ml", link:"https://www.youtube.com/watch?v=VMj-3S1tku0" },
        { id:"w3m5", text:"Sign up for OpenAI API key", type:"setup", link:"https://platform.openai.com/api-keys" },
        { id:"w3m6", text:"Sign up for Anthropic API key", type:"setup", link:"https://console.anthropic.com/" },
        { id:"w3m7", text:"Make FIRST LLM API call (OpenAI SDK)", type:"llm", link:"https://platform.openai.com/docs/quickstart" },
        { id:"w3m8", text:"Build: terminal chatbot with OpenAI", type:"project" },
      ]},
      { day: "Tue", tag: "DRIVE 5-9", tasks: [
        { id:"w3t1", text:"LC: Search in Rotated Sorted Array (Medium)", type:"dsa", link:"https://leetcode.com/problems/search-in-rotated-sorted-array/" },
        { id:"w3t2", text:"LC: Time Based Key-Value Store (Medium)", type:"dsa", link:"https://leetcode.com/problems/time-based-key-value-store/" },
        { id:"w3t3", text:"Karpathy Micrograd (finish) — code along", type:"ml", link:"https://www.youtube.com/watch?v=VMj-3S1tku0" },
        { id:"w3t4", text:"Extend chatbot: add conversation history", type:"project" },
        { id:"w3t5", text:"Anthropic Prompt Tutorial: Chapters 1-3", type:"llm", link:"https://github.com/anthropics/prompt-eng-interactive-tutorial" },
      ]},
      { day: "Wed", tag: "NO DRIVE", tasks: [
        { id:"w3w1", text:"LC: Valid Parentheses (Easy)", type:"dsa", link:"https://leetcode.com/problems/valid-parentheses/" },
        { id:"w3w2", text:"LC: Min Stack (Medium)", type:"dsa", link:"https://leetcode.com/problems/min-stack/" },
        { id:"w3w3", text:"LC: Evaluate Reverse Polish Notation (Medium)", type:"dsa", link:"https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
        { id:"w3w4", text:"Anthropic Prompt Tutorial: Ch 4-9 (finish)", type:"llm", link:"https://github.com/anthropics/prompt-eng-interactive-tutorial" },
        { id:"w3w5", text:"Build: prompt tester — 5 variants, compare", type:"project" },
        { id:"w3w6", text:"Push 'prompt-tester' repo to GitHub", type:"project" },
      ]},
      { day: "Thu", tag: "DRIVE 5-9", tasks: [
        { id:"w3h1", text:"LC: Generate Parentheses (Medium)", type:"dsa", link:"https://leetcode.com/problems/generate-parentheses/" },
        { id:"w3h2", text:"LC: Daily Temperatures (Medium)", type:"dsa", link:"https://leetcode.com/problems/daily-temperatures/" },
        { id:"w3h3", text:"OpenAI Prompt Engineering Guide", type:"llm", link:"https://platform.openai.com/docs/guides/prompt-engineering" },
        { id:"w3h4", text:"Build: document summarizer (chain-of-thought)", type:"project" },
        { id:"w3h5", text:"Learn: token counting with tiktoken", type:"llm", link:"https://github.com/openai/tiktoken" },
      ]},
      { day: "Fri", tag: "DRIVE 4-9", tasks: [
        { id:"w3f1", text:"LC: Car Fleet (Medium)", type:"dsa", link:"https://leetcode.com/problems/car-fleet/" },
        { id:"w3f2", text:"Add streaming to chatbot (stream=True)", type:"llm", link:"https://platform.openai.com/docs/api-reference/streaming" },
        { id:"w3f3", text:"Read: OpenAI + Anthropic pricing pages", type:"llm", link:"https://openai.com/api/pricing" },
        { id:"w3f4", text:"WEEKLY RETRO: log hours, push code", type:"review" },
      ]},
      { day: "Sat", tag: "DRIVE 12-8", tasks: [
        { id:"w3s1", text:"LC Review: Binary Search + 2 Stack probs", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w3s2", text:"LC: Largest Rectangle in Histogram (Hard)", type:"dsa", link:"https://leetcode.com/problems/largest-rectangle-in-histogram/" },
        { id:"w3s3", text:"Build: FastAPI + LLM endpoint with streaming", type:"project", link:"https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse" },
      ]},
      { day: "Sun", tag: "DRIVE 12-8", tasks: [
        { id:"w3u1", text:"Drill weakest pattern: 3 problems timed", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w3u2", text:"Karpathy Ep 2: Makemore Part 1 (start)", type:"ml", link:"https://www.youtube.com/watch?v=PaCmpygFfXo" },
        { id:"w3u3", text:"Polish FastAPI+LLM: error handling, retries", type:"project", link:"https://tenacity.readthedocs.io/" },
        { id:"w3u4", text:"Push everything, plan Week 4", type:"review" },
      ]},
    ],
  },
  {
    id: 4, title: "Linked Lists, Trees & Tool Calling", accent: "#A855F7",
    days: [
      { day: "Mon", tag: "NO DRIVE", tasks: [
        { id:"w4m1", text:"LC: Reverse Linked List (Easy)", type:"dsa", link:"https://leetcode.com/problems/reverse-linked-list/" },
        { id:"w4m2", text:"LC: Merge Two Sorted Lists (Easy)", type:"dsa", link:"https://leetcode.com/problems/merge-two-sorted-lists/" },
        { id:"w4m3", text:"LC: Linked List Cycle (Easy)", type:"dsa", link:"https://leetcode.com/problems/linked-list-cycle/" },
        { id:"w4m4", text:"Karpathy Ep 2: Makemore (finish)", type:"ml", link:"https://www.youtube.com/watch?v=PaCmpygFfXo" },
        { id:"w4m5", text:"Read: OpenAI Structured Outputs Guide", type:"llm", link:"https://platform.openai.com/docs/guides/structured-outputs" },
        { id:"w4m6", text:"Install Instructor library", type:"setup", link:"https://python.useinstructor.com/" },
        { id:"w4m7", text:"Build: invoice parser — text → Pydantic model", type:"project" },
      ]},
      { day: "Tue", tag: "DRIVE 5-9", tasks: [
        { id:"w4t1", text:"LC: Reorder List (Medium)", type:"dsa", link:"https://leetcode.com/problems/reorder-list/" },
        { id:"w4t2", text:"LC: Remove Nth Node From End (Medium)", type:"dsa", link:"https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
        { id:"w4t3", text:"Study: Pydantic models, validators", type:"llm", link:"https://docs.pydantic.dev/latest/" },
        { id:"w4t4", text:"Build: structured data extractor", type:"project", link:"https://python.useinstructor.com/" },
        { id:"w4t5", text:"Read: OpenAI Function Calling Guide", type:"llm", link:"https://platform.openai.com/docs/guides/function-calling" },
        { id:"w4t6", text:"Read: Anthropic Tool Use docs", type:"llm", link:"https://docs.anthropic.com/en/docs/build-with-claude/tool-use" },
      ]},
      { day: "Wed", tag: "NO DRIVE", tasks: [
        { id:"w4w1", text:"LC: Invert Binary Tree (Easy)", type:"dsa", link:"https://leetcode.com/problems/invert-binary-tree/" },
        { id:"w4w2", text:"LC: Max Depth of Binary Tree (Easy)", type:"dsa", link:"https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
        { id:"w4w3", text:"LC: Same Tree (Easy)", type:"dsa", link:"https://leetcode.com/problems/same-tree/" },
        { id:"w4w4", text:"LC: Subtree of Another Tree (Easy)", type:"dsa", link:"https://leetcode.com/problems/subtree-of-another-tree/" },
        { id:"w4w5", text:"Karpathy Ep 3: Makemore MLP (first half)", type:"ml", link:"https://www.youtube.com/watch?v=TCH_1BHY58I" },
        { id:"w4w6", text:"BUILD: assistant with 3 tools", type:"project", link:"https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb" },
        { id:"w4w7", text:"Wire full tool calling loop", type:"project" },
      ]},
      { day: "Thu", tag: "DRIVE 5-9", tasks: [
        { id:"w4h1", text:"LC: Lowest Common Ancestor BST (Medium)", type:"dsa", link:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
        { id:"w4h2", text:"LC: Binary Tree Level Order (Medium)", type:"dsa", link:"https://leetcode.com/problems/binary-tree-level-order-traversal/" },
        { id:"w4h3", text:"Karpathy Ep 3 (finish)", type:"ml", link:"https://www.youtube.com/watch?v=TCH_1BHY58I" },
        { id:"w4h4", text:"Add 4th tool: query_database(sql)", type:"project" },
        { id:"w4h5", text:"Add multi-turn conversation to assistant", type:"project", link:"https://platform.openai.com/docs/guides/conversation-state" },
      ]},
      { day: "Fri", tag: "DRIVE 4-9", tasks: [
        { id:"w4f1", text:"LC: Validate BST (Medium)", type:"dsa", link:"https://leetcode.com/problems/validate-binary-search-tree/" },
        { id:"w4f2", text:"Add streaming to tool-calling assistant", type:"project" },
        { id:"w4f3", text:"Read: Tenacity — add retry logic", type:"llm", link:"https://tenacity.readthedocs.io/" },
        { id:"w4f4", text:"WEEKLY RETRO + MONTH 1 REVIEW", type:"review" },
      ]},
      { day: "Sat", tag: "DRIVE 12-8", tasks: [
        { id:"w4s1", text:"LC timed: 1 LL + 1 Tree + 1 old problem", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w4s2", text:"LC: LRU Cache (Medium) — classic!", type:"dsa", link:"https://leetcode.com/problems/lru-cache/" },
        { id:"w4s3", text:"Polish tool-calling assistant + README", type:"project" },
        { id:"w4s4", text:"fast.ai Lesson 3: Neural Net Foundations", type:"ml", link:"https://course.fast.ai/" },
      ]},
      { day: "Sun", tag: "DRIVE 12-8", tasks: [
        { id:"w4u1", text:"Drill WEAKEST pattern: 3 problems", type:"dsa", link:"https://neetcode.io/practice" },
        { id:"w4u2", text:"fast.ai Lesson 3 (continue)", type:"ml", link:"https://course.fast.ai/" },
        { id:"w4u3", text:"Deploy tool-calling assistant as FastAPI", type:"project" },
        { id:"w4u4", text:"MONTH 1 FINAL: push code, clean READMEs", type:"review" },
      ]},
    ],
  },
];

export const ROUTINE = {
  Mon: [
    {t:"7:30",l:"Wake · Breakfast",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode (2.5h)",c:"#EF4444"},{t:"12:00",l:"ML/LLM Theory (1.25h)",c:"#3B82F6"},
    {t:"1:30",l:"Commute to class",c:"#52525B"},{t:"3:00",l:"Study (1h)",c:"#3B82F6"},
    {t:"5:00",l:"CLASS",c:"#FBBF24"},{t:"6:20",l:"Commute back",c:"#52525B"},
    {t:"8:00",l:"Dinner",c:"#333"},{t:"8:20",l:"DEEP BUILD (3h)",c:"#10B981"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"Light review",c:"#EF4444"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
  Tue: [
    {t:"7:30",l:"Wake · Breakfast",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode (2.25h)",c:"#EF4444"},{t:"11:45",l:"ML quick (30m)",c:"#3B82F6"},
    {t:"12:30",l:"CLASS",c:"#FBBF24"},{t:"1:50",l:"Commute back · Lunch",c:"#52525B"},
    {t:"3:00",l:"BUILD (1.75h)",c:"#10B981"},{t:"5:00",l:"DRIVE GrubHub (4h)",c:"#FB7185"},
    {t:"9:00",l:"Dinner",c:"#333"},{t:"9:20",l:"LLM + Build (2h)",c:"#A855F7"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"LC review",c:"#EF4444"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
  Wed: [
    {t:"7:30",l:"Wake · Breakfast",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode (2.5h)",c:"#EF4444"},{t:"12:00",l:"ML/LLM Theory (1.25h)",c:"#3B82F6"},
    {t:"1:30",l:"Commute to class",c:"#52525B"},{t:"3:00",l:"Study (1h)",c:"#3B82F6"},
    {t:"5:00",l:"CLASS",c:"#FBBF24"},{t:"6:20",l:"Commute back",c:"#52525B"},
    {t:"8:00",l:"Dinner",c:"#333"},{t:"8:20",l:"DEEP BUILD (3h)",c:"#10B981"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"Light review",c:"#EF4444"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
  Thu: [
    {t:"7:30",l:"Wake · Breakfast",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode (2.25h)",c:"#EF4444"},{t:"11:45",l:"ML quick (30m)",c:"#3B82F6"},
    {t:"12:30",l:"CLASS",c:"#FBBF24"},{t:"1:50",l:"Commute back · Lunch",c:"#52525B"},
    {t:"3:00",l:"BUILD (1.75h)",c:"#10B981"},{t:"5:00",l:"DRIVE GrubHub (4h)",c:"#FB7185"},
    {t:"9:00",l:"Dinner",c:"#333"},{t:"9:20",l:"LLM + Build (2h)",c:"#A855F7"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"LC review",c:"#EF4444"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
  Fri: [
    {t:"7:30",l:"Wake · Breakfast",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode (1.25h)",c:"#EF4444"},{t:"11:00",l:"CLASS (3h)",c:"#FBBF24"},
    {t:"2:00",l:"Lunch",c:"#333"},{t:"2:15",l:"Build + ML (1.5h)",c:"#10B981"},
    {t:"4:00",l:"DRIVE GrubHub (5h)",c:"#FB7185"},{t:"9:00",l:"Dinner",c:"#333"},
    {t:"9:20",l:"Retro + LLM (2h)",c:"#A855F7"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"Light reading",c:"#3B82F6"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
  Sat: [
    {t:"7:30",l:"Wake · Big breakfast",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode DEEP (2.25h)",c:"#EF4444"},
    {t:"12:00",l:"DRIVE GrubHub (8h)",c:"#FB7185"},{t:"8:00p",l:"Dinner",c:"#333"},
    {t:"8:20",l:"Build + LLM (3h)",c:"#10B981"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"Light review",c:"#EF4444"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
  Sun: [
    {t:"7:30",l:"Wake · Fuel up",c:"#333"},{t:"8:00",l:"GYM (1.5h)",c:"#F59E0B"},
    {t:"9:30",l:"LeetCode drill (2.25h)",c:"#EF4444"},
    {t:"12:00",l:"DRIVE GrubHub (8h)",c:"#FB7185"},{t:"8:00p",l:"Dinner",c:"#333"},
    {t:"8:20",l:"Plan + Build (3h)",c:"#10B981"},
    {t:"11:30",l:"WALK (30m)",c:"#06B6D4"},{t:"12:00",l:"Light reading",c:"#3B82F6"},{t:"12:30",l:"Sleep",c:"#222"},
  ],
};

export const TYPES = {
  dsa:     { a:"#EF4444", bg:"#2D0A0A", l:"DSA",    i:"⚡" },
  ml:      { a:"#3B82F6", bg:"#0C1929", l:"ML",     i:"🧠" },
  llm:     { a:"#A855F7", bg:"#1A0A30", l:"LLM",    i:"🤖" },
  project: { a:"#10B981", bg:"#05200F", l:"BUILD",  i:"🔨" },
  review:  { a:"#F59E0B", bg:"#1F1505", l:"REVIEW", i:"📋" },
  setup:   { a:"#6B7280", bg:"#1a1a1f", l:"SETUP",  i:"⚙️" },
};
